### ISSUE TITLE
`@container` is stripped by the Vite CSS generation

### ISSUE THREAD

**Issue by zackkatz** [UseDataKit/SDK#39]
The SCSS in DataViews declares that when a container is less than 480px wide, there should be a 48px padding: https://github.com/WordPress/gutenberg/blob/843e14b0e7768117ca6571bd009d04f522b63374/packages/dataviews/src/dataviews-layouts/table/style.scss#L179-L189

This `@container` declaration references the `.dataviews-wrapper` rule, which has `container: dataviews-wrapper/inline-size;` set.

The `@container` is getting stripped from the CSS we generate, so the padding remains:

```css
.dataviews-view-table tr td:first-child,
.dataviews-view-table tr th:first-child {
  padding-left:48px
}
```

This was reported by @westguard.
